#!/usr/bin/env python3
"""godot-context — generate/refresh a Godot project CLAUDE.md from discovered facts.

Discovers the Godot binary + version, parses project.godot (name, config version,
language, autoloads), and emits a CLAUDE.md scaffold seeded with the AI-leverageable
architecture rules. TODO markers flag the sections a human/agent must curate (the script
cannot infer game-specific architecture). No-overwrite unless --force.

Usage:
  python generate_context.py <project_dir> [--out CLAUDE.md] [--force] [--stdout]
Env:
  GODOT_BIN  overrides binary discovery
Exit: 0 ok · 2 usage/no project.godot · 3 refused overwrite
"""
import argparse
import os
import re
import shutil
import subprocess
import sys

STEAM = r"C:\Program Files (x86)\Steam\steamapps\common\Godot Engine\godot.windows.opt.tools.64.exe"


def discover_binary():
    b = os.environ.get("GODOT_BIN")
    if b and os.path.exists(b):
        return b
    for n in ("godot", "godot4", "Godot", "godot.exe"):
        p = shutil.which(n)
        if p:
            return p
    if os.path.exists(STEAM):
        return STEAM
    return None


def binary_version(binary):
    if not binary:
        return "unknown"
    try:
        r = subprocess.run([binary, "--headless", "--version"],
                           capture_output=True, text=True, timeout=60)
        out = (r.stdout or r.stderr or "").strip()
        return out.splitlines()[0] if out else "unknown"
    except Exception:
        return "unknown"


def parse_project(proj):
    facts = {"name": "(unnamed)", "config_version": "?", "language": "GDScript",
             "autoloads": [], "features": ""}
    pg = os.path.join(proj, "project.godot")
    if not os.path.isfile(pg):
        return facts, False
    text = open(pg, encoding="utf-8", errors="replace").read()
    m = re.search(r'config/name="([^"]*)"', text)
    if m:
        facts["name"] = m.group(1)
    m = re.search(r'config_version=(\d+)', text)
    if m:
        facts["config_version"] = m.group(1)
    m = re.search(r'config/features=PackedStringArray\(([^)]*)\)', text)
    if m:
        facts["features"] = m.group(1).replace('"', "").strip()
    aut = re.search(r'\[autoload\](.*?)(\n\[|\Z)', text, re.S)
    if aut:
        for line in aut.group(1).splitlines():
            mm = re.match(r'\s*([A-Za-z_]\w*)\s*=', line)
            if mm:
                facts["autoloads"].append(mm.group(1))
    try:
        has_csproj = any(f.endswith(".csproj") for f in os.listdir(proj))
    except OSError:
        has_csproj = False
    facts["language"] = "C# (GodotSharp)" if ("[dotnet]" in text or has_csproj) else "GDScript"
    return facts, True


def render(facts, binary, version):
    autoloads = facts["autoloads"]
    autoload_lines = "\n".join("- `%s` — TODO: responsibility" % a for a in autoloads) \
        if autoloads else "- TODO: list autoloads (singletons) in dependency order"
    bin_display = binary or "(not found — set $GODOT_BIN)"
    is_gd = facts["language"].startswith("GDScript")
    lang_rules_title = "GDScript 4.x rules" if is_gd else "C# / GodotSharp rules (note: target is GDScript-first)"
    lang_rules = (
        "- Signals: `signal x` · `x.emit()` · `x.connect(callable)` — NOT Godot-3 "
        "`connect(\"x\", self, \"m\")`.\n"
        "- No Godot-3 idioms: no `yield` (use `await`), no `export var` (use `@export`), no `setget`.\n"
        "- Typed everywhere: `var n: int`, `func f(x: float) -> void`. Use `@onready`, `@export`.\n"
        "- `const` containers are parse-time only — use `static var` for typed Array/Dictionary with methods.\n"
        "- Deterministic RNG: `RandomNumberGenerator` with explicit `.seed`/`.state`; one stream per concern.\n"
        "- File I/O: `FileAccess`; saves are atomic (temp file then rename)."
        if is_gd else
        "- Use GodotSharp 4.x APIs; cache `StringName`s for hot paths; respect `Dispose()` vs `Free()` for RefCounted.\n"
        "- Deterministic RNG: a seeded generator per concern; quarantine non-deterministic randomness."
    )
    return f"""# CLAUDE.md — {facts['name']}

> Project context for AI coding assistants. **This file is the source of truth** an agent
> reads first; keep it current. *(Generated by `godot-context`; curate the TODO sections.)*

## Engine & build
- Engine: **{version}** (project `config_version={facts['config_version']}`{', features: ' + facts['features'] if facts['features'] else ''})
- Language: **{facts['language']}**
- Godot binary (discovered; not assumed on PATH): `{bin_display}`
  - Convention: resolve `$GODOT_BIN` → PATH → the path above. Never assume a bare `godot`.

## Commands
```bash
# Open editor
"$GODOT_BIN" --editor --path .
# Run the game
"$GODOT_BIN" --path .
# Headless import (build class cache)
"$GODOT_BIN" --headless --path . --import
# Run tests (after GUT is installed) — TODO: confirm test runner
"$GODOT_BIN" --headless --path . -s res://addons/gut/gut_cmdln.gd -gexit
```

## Architecture (autoloads / singletons)
{autoload_lines}

## Deterministic update order
TODO: list the single deterministic update loop step-by-step (the order systems run each
tick). Player input and cosmetic randomness stay OUTSIDE this order.

## {lang_rules_title}
{lang_rules}

## Non-negotiables (do NOT let an assistant violate these)
- **Determinism is quarantined** — gameplay uses seeded, per-concern RNG; cosmetic/non-gameplay
  randomness is separate and never affects saved state.
- **Data-driven content** — definitions live in data (`.gd` tables / `Resource`), separate from
  runtime instances. Add content as data, not new control-flow branches.
- **Compose, don't special-case** — effects/modifiers resolve through one pipeline
  (additive → multiplicative → cap → clamp). Never write pairwise "if A and B" special cases.
- **Intent vs logic** — player intent is an action/command queued + executed; game logic is
  separate. Keep the seam.
- **Test seams** — inject RNG/seed and stores so systems are testable headlessly.

## Conventions
TODO: naming (e.g. node-class prefix), directory layout, signal hygiene, save/migration rules.

<!-- Regenerate facts with `godot-context`; curate TODO sections by hand. Drift fuse:
     re-verify the engine version + binary path if the build moves. -->
"""


def main(argv):
    for stream in (sys.stdout, sys.stderr):
        try:
            stream.reconfigure(encoding="utf-8")  # Windows consoles default to cp1252
        except Exception:
            pass
    ap = argparse.ArgumentParser()
    ap.add_argument("project_dir")
    ap.add_argument("--out", default="CLAUDE.md")
    ap.add_argument("--force", action="store_true")
    ap.add_argument("--stdout", action="store_true")
    args = ap.parse_args(argv[1:])

    proj = os.path.abspath(args.project_dir)
    facts, ok = parse_project(proj)
    if not ok:
        print("godot-context: no project.godot in %s" % proj)
        return 2
    binary = discover_binary()
    version = binary_version(binary)
    content = render(facts, binary, version)

    if args.stdout:
        sys.stdout.write(content)
        return 0
    out_path = os.path.join(proj, args.out)
    if os.path.exists(out_path) and not args.force:
        print("godot-context: %s exists — refusing to overwrite (use --force or curate by hand)" % out_path)
        print("--- proposed content follows on stdout ---")
        sys.stdout.write(content)
        return 3
    open(out_path, "w", encoding="utf-8").write(content)
    print("godot-context: wrote %s (engine=%s, language=%s, autoloads=%d)"
          % (out_path, version, facts["language"], len(facts["autoloads"])))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
